# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/run_vivado/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/run_vivado/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/run_vivado/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soft/func/obj/inst_ram.coe
read_verilog C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/defines.vh
read_verilog -library xil_defaultlib {
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/adder.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/alu.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/aludec.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/BRIDGE/bridge_1x2.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/CONFREG/confreg.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/controller.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/cp0_reg.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/datapath.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/div.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/div_state.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/eqcmp.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/exception.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/exceptpc.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/flopenr.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/flopenrc.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/floprc.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/hazard.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/hilo_reg.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/maindec.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/memsel.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/mips.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/mux2.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/mux3.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/mux4.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/pc.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/regfile.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/signext.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/sl2.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/myCPU/top.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/soc_lite_top.v
}
read_ip -quiet C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/xilinx_ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc]

read_ip -quiet C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/xilinx_ip/inst_ram/inst_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/xilinx_ip/inst_ram/inst_ram_ooc.xdc]

read_ip -quiet C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/xilinx_ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/run_vivado/soc_lite.xdc
set_property used_in_implementation false [get_files C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/func_test_v0.01/soc_sram_func/run_vivado/soc_lite.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_lite_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_lite_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_lite_top_utilization_synth.rpt -pb soc_lite_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
