# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/run_vivado/mycpu_prj1/mycpu.cache/wt [current_project]
set_property parent.project_path C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/run_vivado/mycpu_prj1/mycpu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
add_files C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soft/perf_func/obj/allbench/axi_ram.coe
read_verilog {
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/defines.vh
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/defines_ascii.vh
}
read_verilog -library xil_defaultlib {
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/ALU.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/ALU_Decoder.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/Comparer.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/Controller.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/DataPath.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/Div_32x32.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/ImmShift.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/Imm_Extend.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/InstAsciiDecoder.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/MUL.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/MainDecoder.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/Mux_21.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/Mux_41.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/PC.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/PCAdd.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/PipeReg.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/RegHILO.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/RegHeap.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/axi_interface.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/axi_wrap/axi_wrap.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/ram_wrap/axi_wrap_ram.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/CONFREG/confreg.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/cp0_reg.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/d_chche.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/exception.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/hazard.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/i_cache.v
  C:/Users/xiang/Desktop/func_test_v0.03/func_test_v0.03/soc_axi_func/rtl/myCPU/mips.v
  C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/soc_axi_lite_top.v
}
read_ip -quiet C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_ram/axi_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_ram/axi_ram_ooc.xdc]

read_ip -quiet C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc]

read_ip -quiet C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter.xci
set_property used_in_synthesis false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_ooc.xdc]

read_ip -quiet C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
set_property used_in_implementation false [get_files -all c:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/run_vivado/soc_lite.xdc
set_property used_in_implementation false [get_files C:/Users/xiang/Downloads/full_v0.04/test/n4ddr/perf_test_v0.01/soc_axi_perf/run_vivado/soc_lite.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_axi_lite_top -part xc7a100tcsg324-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_axi_lite_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_axi_lite_top_utilization_synth.rpt -pb soc_axi_lite_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
